### ISSUE TITLE
Setup Deployment

### ISSUE THREAD

**Issue by cdeiac** [UZHASE/bnbexplorer-backend#4]
Setup deployment pipelines, including config files.
Suggestion: Use Travis CI + Heroku, as it is included in GitHub Students pack. But we can also explore other options.

**Comment by julwil** [comment]
Done
See [https://bnbexplorer-frontend.herokuapp.com/](https://bnbexplorer-frontend.herokuapp.com/)
See [https://bnbexplorer-backend.herokuapp.com/](https://bnbexplorer-backend.herokuapp.com/)
