### ISSUE TITLE
GET /listings/metadata

### ISSUE THREAD

**Issue by PKiechl** [UZHASE/bnbexplorer-backend#45]
Request for a new endpoint, that delivers metadata drawn from the entire pool of the listings. Metadata that would currently be needed (list might get extended as we work through the filters):

- global minPrice
- global maxPrice
- number of listings
- list of possible areas
- list of possible neighbourhoods
- list of possible roomtypes
- global max number of listings per host

The reason why this (in our opinion) is best done in the backend, is that we want to have some sort of default filter settings, which thus are already applied to our initial GET request to GET /listings. Therefore, however, the initial filter settings (like in the example of min and max prices) automatically limit the price-range of the listings that will be returned, hence calculating a dynamic min/max in the frontend will always yield the values of either the default-filter or, if the filter-settings were changed, those of the changed price-range filter.

There are ways to work around that by e.g. always calling the GET /listings endpoint without any filter-settings and then again with filter-settings, but that (_i_) feels like a half-baked workaround and (_ii_) leads to unnecessary network traffic.

We can also discuss this on friday in the meeting, I just wanted to place this here so we don't forget :).

**Comment by julwil** [comment]
@PKiechl Done. See linked PR
