### ISSUE TITLE
listingsPerHost in Query raises error for recommendations

### ISSUE THREAD

**Issue by fabiank0** [UZHASE/bnbexplorer-backend#57]
See below the trace:
backend   | 172.18.0.1 - - [08/May/2021 11:16:11] "GET /api/v1/airbnb-explorer/listings/recommendations?listingId=26062650&priceMin=50&priceMax=100&minNights=5&availablility=5&listingsPerHost=1 HTTP/1.1" 500 -
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
...
backend   | sqlite3.OperationalError: no such column: hosts.num_of_listings

**Comment by cdeiac** [comment]
@julwil I just created a PR for it right when you assigned it to yourself  😅
