### ISSUE TITLE
ValueError: The provided filter criteria are too restrictive!

### ISSUE THREAD

**Issue by fabiank0** [UZHASE/bnbexplorer-backend#62]
Hi, this query returns a ValueError: 

http://localhost:8080/api/v1/airbnb-explorer/listings/recommendations?listingId=32990282&hostId=30698503&priceMin=50&priceMax=100&minNights=5&availability=90

<img width="2528" alt="Screenshot 2021-05-15 at 11 56 29" src="https://user-images.githubusercontent.com/43517763/118356257-970d5800-b574-11eb-8db7-dd7675d041c7.png">

Is the problem that no similar listings were found?

**Comment by cdeiac** [comment]
This message indicates that the number of Listings matching the provided criteria are less than 5 (which we need at least, since we always return 5 recommendations).
In this case, there is only a single Listing that matches e.g., the given hostId, so thats why you get the error.

We could change the method to return an empty list in such cases, if you prefer that.

**Comment by fabiank0** [comment]
Hi, 
I've just checked and this error occurs almost every time a hostId is sent in the query, even if this host has multiple listings. So if this complicates things, I think it would be better to not take the host into consideration for the computation of the recommendations?

**Comment by fabiank0** [comment]
I think the best solution would be that if less than 5 listings were found, we will catch that and send a different query that does not contain the hostId. This way we can ensure that we always have some recommendations to show.
So, I'd prefer if you could return an empty array, this would make it easier for us to apply this logic, since we wouldn't need to rely on a catch block to catch this specific error.

**Comment by cdeiac** [comment]
Sure thats fine, I can do that.
I just checked our data, 99% of our hosts only have 1 Listing and in some rare cases they have 2 or 3.  So I agree that we can remove the filter by hostId, as it is too restrictive anyways.

**Comment by fabiank0** [comment]
I think we can keep it though, for those <1% cases where it does influence the search.

**Comment by cdeiac** [comment]
I meant just for the recommendations endpoint. Whenever we provide a hostId we will get an empty list back, because no Host has enough Listings to compute 5 recommendations.

**Comment by fabiank0** [comment]
There are actually, i.e. when I set the filter for 10+ listings about 33% have recommendations based on that. So I'd like to keep it if possible.

e.g. here all the recommendations are from the same Host. 
![Screenshot 2021-05-15 at 13 14 28](https://user-images.githubusercontent.com/43517763/118358519-7d254280-b57f-11eb-8c5c-2f69e526a701.png)

**Comment by PKiechl** [comment]
I think it would be better to maintain the hostId for those cases where it actually is applicable. If it is too cumbersome to do so in the backend, we can also try-catch and simply send the modified request, if we get the error from the server :)

**Comment by cdeiac** [comment]
Yes, you are completely right (there is even one host with id 219517861 that has 49 Listings), I just didn't sort properly.

I just made the change that we return an empty list instead of an Error, so thats it ;)

**Comment by fabiank0** [comment]
Thanks!
